### ISSUE TITLE
dns servers cannot be removed

### ISSUE THREAD

**Issue by n0rad** [terraform-routeros/terraform-provider-routeros#174]
from:
```hcl
resource "routeros_dns" "dns-server" {
  allow_remote_requests = true
  servers               = "8.8.8.8,8.8.4.4,1.1.1.1,1.0.0.1"
  use_doh_server        = "https://dns.google/dns-query"
  verify_doh_cert       = false
}
```
to:
```hcl
resource "routeros_dns" "dns-server" {
  allow_remote_requests = true
  servers               = ""
  use_doh_server        = "https://dns.google/dns-query"
  verify_doh_cert       = false
}
```

> No changes.

**Comment by vaerh** [comment]
Hi! It's not really a bug, since this resource is a system resource. That is, we do not know from what state we changed it to what state to return it. I can do a cleanup of Servers, Dynamic Servers, Verify DoH Certificate.

**Comment by n0rad** [comment]
I did not look at how the provider is working internally, so it may be more difficult to implement for a system resource.
But from a user point of view, on the mikrotik, I can empty the `servers` list and I think the provider should mimic the same behavior.

BTW, thx for the provider it's super useful.

**Comment by vaerh** [comment]
Okay, I think this kind of behavior might be necessary for more than just this resource. I'll think about how to do it better and try to make changes this week.
P.S. System resources, from the provider's current point of view, are not to be created or deleted, only read or updated. This is what is implemented internally. The deletion simply deletes the resource record without any action on the router.

**Comment by vaerh** [comment]
@n0rad I want to ask you to test the release on a real state file (the resource has changed its Id generation scheme, but that shouldn't be a problem).

**Comment by vaerh** [comment]
Oh yeah, I came up with an easier problem myself and solved it 🤦 I'm sorry! 
Do we keep restoring properties on deletion or do I return it as it was in the new revision?

**Comment by vaerh** [comment]
@n0rad I fixed the broken operating logic. Let's hope it doesn't cause problems with managing existing resources. 
Thanks for the PR. A large layer of problems has opened up!

Please test the current provider behavior after the release.

**Comment by n0rad** [comment]
:wave: 
Just tested adding servers, then trying to remove them.
Sadly it's still not working, it's still silently ignored.

**Comment by vaerh** [comment]
Yes, this problem was not present in yesterday's synthetic tests. I was able to reproduce it. A little patience and we will fix it :)

**Comment by n0rad** [comment]
working perfectly, with empty string and removing the field.
thx a lot!
