### ISSUE TITLE
Wrong field names in example files

### ISSUE THREAD

**Issue by artashesbalabekyan** [terraform-routeros/terraform-provider-routeros#218]
There are many wrong variable names in example files.

For example:
The resource 'routeros_ip_firewall_mangle' requires the 'new_mss' field. But in examples files it is defined as 'new-mss'.
It causes the problems for converting the examples from HCL to another programming languages. Because the symbol '-' can't be used as a variable name.

It is actual when using tfgen for converting the provider for Pulumi use.

**Comment by vaerh** [comment]
Thank you!
The documentation is fixed. I found problems in only one example file that you wrote about. If you find more errors please reopen this PR.

**Comment by artashesbalabekyan** [comment]
Here is not fixed.
https://github.com/terraform-routeros/terraform-provider-routeros/blob/main/docs/resources/ip_firewall_mangle.md?plain=1

**Comment by vaerh** [comment]
The documentation will automatically be updated after the release. Please have some patience, I will fix the CI today.

**Comment by artashesbalabekyan** [comment]
@vaerh  Thank you very much 🎉
